tickers = [
    "3MINDIA.NS", "AARTIIND.NS", "BBTC.NS", "BHARATFORG.NS", "CHOLAHLDNG.NS", "CRISIL.NS", "DHANI.NS", "HAL.NS", "IDFCFIRSTB.NS", "JKCEMENT.NS",
    "M&MFIN.NS", "SKFINDIA.NS", "TATACHEM.NS", "TVSMOTOR.NS", "WHIRLPOOL.NS", "JSWENERGY.NS", "RECLTD.NS", "TATAPOWER.NS", "GICRE.NS", "IIFLWAM.NS",
    "MINDAIND.NS", "TATACOMM.NS", "ABFRL.NS", "ASHOKLEY.NS", "BANKBARODA.NS", "GSPL.NS", "GUJGASLTD.NS", "IBULHSGFIN.NS", "LALPATHLAB.NS", "PAGEIND.NS",
    "SUNDRMFAST.NS", "TTKPRESTIG.NS", "VINATIORGA.NS", "ABCAPITAL.NS", "AKZOINDIA.NS", "AMARAJABAT.NS", "ASTRAZEN.NS", "BATAINDIA.NS", "CANBK.NS", "COROMANDEL.NS",
    "CUMMINSIND.NS", "ENDURANCE.NS", "GLAXO.NS", "JMFINANCIL.NS", "MPHASIS.NS", "OFSS.NS", "PERSISTENT.NS", "PFIZER.NS", "PGHL.NS", "SRTRANSFIN.NS",
    "SUNTV.NS", "THERMAX.NS", "APLLTD.NS", "BHEL.NS", "DIXON.NS", "GLENMARK.NS", "JINDALSTEL.NS", "L&TFH.NS", "OBEROIRLTY.NS", "PIIND.NS",
    "SANOFI.NS", "EMAMILTD.NS", "ESCORTS.NS", "FORTIS.NS", "GMRINFRA.NS", "HINDZINC.NS", "INDHOTEL.NS", "NHPC.NS", "SCHAEFFLER.NS", "SUPREMEIND.NS",
    "BANKINDIA.NS", "CHOLAFIN.NS", "EXIDEIND.NS", "IDBI.NS", "ISEC.NS", "MANAPPURAM.NS", "METROPOLIS.NS", "MOTILALOFS.NS", "NATCOPHARM.NS", "SOLARINDS.NS",
    "ZEEL.NS", "AUBANK.NS", "CASTROLIND.NS", "DALBHARAT.NS", "MINDTREE.NS", "POLYCAB.NS", "SAIL.NS", "SUVENPHAR.NS", "TIINDIA.NS", "VGUARD.NS",
    "ASTRAL.NS", "ATGL.NS", "DEEPAKNTR.NS", "LAURUSLABS.NS", "LTTS.NS", "NAVINFLUOR.NS", "BAYERCROP.NS", "CONCOR.NS", "GODREJPROP.NS", "IDEA.NS",
    "PFC.NS", "PRESTIGE.NS", "ABB.NS", "APOLLOTYRE.NS", "BEL.NS", "HATSUN.NS", "NIACL.NS", "RAJESHEXPO.NS", "RELAXO.NS", "SUNDARMFIN.NS",
    "TRENT.NS", "UNIONBANK.NS", "AJANTPHARM.NS", "CESC.NS", "CROMPTON.NS", "FEDERALBNK.NS", "GODREJAGRO.NS", "GODREJIND.NS", "IPCALAB.NS", "KANSAINER.NS",
    "RBLBANK.NS", "SJVN.NS", "SUMICHEM.NS", "ATUL.NS", "CREDITACC.NS", "INDIAMART.NS", "IRCTC.NS", "LICHSGFIN.NS", "OIL.NS", "RAMCOCEM.NS",
    "SYNGENE.NS", "VOLTAS.NS", "AAVAS.NS", "AIAENG.NS", "COFORGE.NS", "HONAUT.NS", "MFSL.NS", "NAM-INDIA.NS", "PHOENIXLTD.NS", "SRF.NS",
    "TATAELXSI.NS", "TORNTPOWER.NS", "BALKRISIND.NS", "CUB.NS", "GILLETTE.NS", "ITI.NS", "MAXHEALTH.NS", "MGL.NS", "VBL.NS", "ZYDUSWELL.NS"
]
bad = ['DHANI.NS', 'IIFLWAM.NS', 'MINDAIND.NS', 'GSPL.NS', 'IBULHSGFIN.NS', 'AKZOINDIA.NS', 'AMARAJABAT.NS', 'SRTRANSFIN.NS', 'L&TFH.NS', 'GMRINFRA.NS', 'ISEC.NS', 'MINDTREE.NS', 'SUVENPHAR.NS']
valid = [t for t in tickers if t not in bad]
import pprint
print("VALID_TICKERS = \\")
pprint.pprint(valid, compact=True)
